name: Compilar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Aceder ao código
        uses: actions/checkout@v4

      - name: 2. Preparar o ambiente (Java 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 3. Limpar bloqueios do computador antigo
        run: |
          rm -f gradle/gradle-daemon-jvm.properties
          sed -i '/org.gradle.java.home/d' gradle.properties || true

      - name: 4. Dar permissão de execução
        run: chmod +x ./gradlew

      - name: 5. Compilar a App
        run: ./gradlew assembleDebug -Dorg.gradle.java.home=$JAVA_HOME

      - name: 6. Guardar o ficheiro APK para download
        uses: actions/upload-artifact@v4
        with:
          name: A_Minha_App_Personalizada
          path: '**/*.apk'
